name: Notify Discord on PR to Staging

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - staging

jobs:
  notify-new-pr:
    if: github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'ready_for_review'
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification for New PR
        uses: Ilshidur/action-discord@master
        with:
          args: |
            New PR to Staging
            • Author: ${{ github.actor }}
            • Title: ${{ github.event.pull_request.title }}
            • PR: ${{ github.event.pull_request.html_url }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_SECRET }}

  notify-updated-pr:
    if: github.event.action == 'synchronize'
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification for Updated PR
        uses: Ilshidur/action-discord@master
        with:
          args: |
            PR Updated in Staging
            • Author: ${{ github.actor }}
            • Title: ${{ github.event.pull_request.title }}
            • PR: ${{ github.event.pull_request.html_url }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_SECRET }}
